### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by thalesfsp** [twpayne/go-darksky#18]
https://github.com/shawntoffel/darksky as

- Go mods
- Lat and Long as floats

Thanks!

**Comment by twpayne** [comment]
I do not maintain a list of Dark Sky libraries in `README.md`. I suggest getting your library added to [the official list](https://darksky.net/dev/docs/libraries).

**Comment by thalesfsp** [comment]
Sorry, this issue was for you to update your README.md, as you state "no other Go library provides all of the following:" :)

**Comment by twpayne** [comment]
OK, I've updated the README in #20 to remove the section.

**Comment by thalesfsp** [comment]
Thanks. also thank you for your time developing ths package! Cheers!
